---
name: CI

on:
  pull_request:
  workflow_dispatch:
  push:
    branches: [master]

jobs:
  python-test:
    runs-on: self-hosted
    steps:
      # This step checks out a copy of your repository.
      - uses: actions/checkout@v3
        with:
          clean: false
      # This step references the directory that contains the action.
      - uses: ./.github/actions/atorch-python-test
  pre-commit:
    runs-on: ubuntu-latest
    steps:
      # This step checks out a copy of your repository.
      - uses: actions/checkout@v3
      # This step references the directory that contains the action.
      - uses: ./.github/actions/atorch-pre-commit
